import {test} from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import jwt from 'jsonwebtoken';
import router from '../../routes/photoPunchRoutes.js';
import User from '../../models/User.js';
import TrainerDailyAttendance from '../../models/TrainerDailyAttendance.js';
import { APP_VERSION } from '../../utils/sessionVersion.js';

test('preview capture is authenticated, geofenced and never writes attendance', async t => {
  const envKeys = ['JWT_SECRET', 'PUNCH_ATTENDANCE_ENABLED', 'PUNCH_CAMPUS_LATITUDE', 'PUNCH_CAMPUS_LONGITUDE', 'PUNCH_IPINFO_TOKEN', 'PUNCH_LOCAL_TRIAL_ALLOW_UNVERIFIED_NETWORK', 'NODE_ENV'];
  const old = Object.fromEntries(envKeys.map(key => [key, process.env[key]]));
  process.env.JWT_SECRET = 'photo-punch-test-secret'; process.env.PUNCH_ATTENDANCE_ENABLED = 'false';
  process.env.PUNCH_CAMPUS_LATITUDE = '13.621069'; process.env.PUNCH_CAMPUS_LONGITUDE = '79.289828'; delete process.env.PUNCH_IPINFO_TOKEN;
  t.after(() => { for (const key of envKeys) { if (old[key] === undefined) delete process.env[key]; else process.env[key] = old[key]; } });
  let role = 'trainer';
  t.mock.method(User, 'findById', () => ({select: async () => ({_id: 'test-user', role, trainer: 'test-trainer', isActive: true, sessionVersion: 1})}));
  let liveWriteAllowed = false, write;
  t.mock.method(TrainerDailyAttendance, 'findOneAndUpdate', async (filter, update) => { assert.equal(liveWriteAllowed, true, 'Preview must never write attendance'); write = {filter, update}; return {}; });
  const app = express(); app.use(express.json()); app.use('/punch', router);
  const server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve));
  t.after(() => {server.closeAllConnections(); server.close();});
  const base = `http://127.0.0.1:${server.address().port}/punch`;
  const auth = jwt.sign({id: 'test-user', sv: 1, av: APP_VERSION}, process.env.JWT_SECRET);
  const headers = {Authorization: `Bearer ${auth}`, 'Content-Type': 'application/json'};
  const location = {latitude: 13.621069, longitude: 79.289828, accuracy: 10, timestamp: Date.now()};
  assert.equal((await fetch(`${base}/config`)).status, 401);
  for (const path of ['/config', '/scheduled-oif', '/capture-session', '/submit', '/test-upload']) {
    assert.equal((await fetch(`${base}${path}`, {method: path.includes('config') || path.includes('scheduled-oif') ? 'GET' : 'POST', headers})).status, 403);
  }
  role = 'admin';
  const outside = await fetch(`${base}/capture-session`, {method: 'POST', headers, body: JSON.stringify({location: {...location, latitude: 14}})});
  assert.equal(outside.status, 400);
  const response = await fetch(`${base}/capture-session`, {method: 'POST', headers, body: JSON.stringify({location})});
  assert.equal(response.status, 200); const session = await response.json(); assert.equal(session.network, 'unknown');
  const jpeg = Buffer.alloc(1100); jpeg.writeUInt16BE(0xffd8, 0); jpeg.writeUInt16BE(0xffc0, 2); jpeg.writeUInt16BE(17, 4);
  jpeg[6] = 8; jpeg.writeUInt16BE(480, 7); jpeg.writeUInt16BE(640, 9); jpeg.writeUInt16BE(0xffd9, jpeg.length - 2);
  const form = new FormData(); form.append('token', session.token); form.append('photo', new Blob([jpeg], {type:'image/jpeg'}), 'test.jpg'); form.append('assignment', JSON.stringify({mode:'it'}));
  const submission = await fetch(`${base}/submit`, {method:'POST', headers:{Authorization:`Bearer ${auth}`}, body:form});
  assert.equal(submission.status, 200); assert.equal((await submission.json()).preview, true);
  const realFetch = globalThis.fetch;
  const driveKeys = ['PUNCH_GOOGLE_CLIENT_ID', 'PUNCH_GOOGLE_CLIENT_SECRET', 'PUNCH_GOOGLE_REFRESH_TOKEN'];
  const oldDrive = driveKeys.map(key => process.env[key]);
  driveKeys.forEach(key => { process.env[key] = 'mock'; });
  t.after(() => driveKeys.forEach((key, i) => { if (oldDrive[i] === undefined) delete process.env[key]; else process.env[key] = oldDrive[i]; }));
  t.mock.method(globalThis, 'fetch', async (url, options) => {
    if (String(url).startsWith('https://oauth2.googleapis.com/')) return Response.json({access_token:'mock'});
    if (String(url).startsWith('https://www.googleapis.com/upload/')) return Response.json({id:'mock-photo', webViewLink:'https://drive.google.com/file/d/mock-photo/view'});
    if (String(url).startsWith('https://www.googleapis.com/drive/')) return Response.json({files:[{id:'mock-folder'}]});
    return realFetch(url, options);
  });
  const uploaded = await fetch(`${base}/test-upload`, {method:'POST', headers:{Authorization:`Bearer ${auth}`}, body:form});
  assert.equal(uploaded.status, 200);
  assert.equal((await uploaded.json()).uploaded, true);
  const invalid = new FormData(); invalid.append('token', 'invalid'); invalid.append('photo', new Blob([jpeg]), 'test.jpg');
  assert.equal((await fetch(`${base}/submit`, {method:'POST', headers:{Authorization:`Bearer ${auth}`}, body:invalid})).status, 400);
  process.env.PUNCH_ATTENDANCE_ENABLED = 'true';
  process.env.PUNCH_LOCAL_TRIAL_ALLOW_UNVERIFIED_NETWORK = 'false';
  process.env.NODE_ENV = 'development';
  assert.equal((await fetch(`${base}/capture-session`, {method:'POST',headers,body:JSON.stringify({location:{...location,timestamp:Date.now()}})})).status,503);
  process.env.PUNCH_LOCAL_TRIAL_ALLOW_UNVERIFIED_NETWORK = 'true';
  const liveCapture = await fetch(`${base}/capture-session`, {method:'POST',headers,body:JSON.stringify({location:{...location,timestamp:Date.now()}})});
  assert.equal(liveCapture.status,200);
  const liveSession = await liveCapture.json();
  const liveForm = new FormData(); liveForm.append('token',liveSession.token); liveForm.append('photo',new Blob([jpeg],{type:'image/jpeg'}),'test.jpg'); liveForm.append('assignment',JSON.stringify({mode:'capsule'}));
  let existing = null;
  t.mock.method(TrainerDailyAttendance,'findOne',() => ({select:() => ({lean:async () => existing})}));
  liveWriteAllowed = true;
  const liveResult = await fetch(`${base}/submit`,{method:'POST',headers:{Authorization:`Bearer ${auth}`},body:liveForm});
  assert.equal(liveResult.status,200);
  assert.equal((await liveResult.json()).preview,false);
  assert.equal(write.update.$set.oifNumber,'CA26421');
  assert.equal(write.update.$set.punchInSource,'toms_camera');
  assert.equal(write.update.$set.photoPunch.driveFileId,'mock-photo');
  existing = {attendanceType:'oif',punchInAt:new Date()};
  assert.equal((await fetch(`${base}/submit`,{method:'POST',headers:{Authorization:`Bearer ${auth}`},body:liveForm})).status,409);
  existing = {attendanceType:'leave'};
  assert.equal((await fetch(`${base}/submit`,{method:'POST',headers:{Authorization:`Bearer ${auth}`},body:liveForm})).status,409);
});
