import { IDSA_SUBJECT, PSTP_SUBJECT, DSAP_SUBJECT } from './trainerMappings.js';
import { PSTJ_SUBJECT_CODE, QAVA_SUBJECT_CODE } from './subjectSlotTimings.js';
import { LRRE_SUBJECT_CODE } from './lrreVSemesterTimetable.js';

export const TOPIC_TRACKER_SPECIAL_TOPICS = ['Revision', 'Class Test'];

export const IDSA_TOPIC_TRACKER_TOPICS = [
  'Introduction to Data structures',
  'Types of Data Structures',
  'Arrays and its types',
  'Problems on Arrays - 1: Insertion of New Product IDs, Second occurrence, Maximum Subarray',
  'Problems on Arrays - 2: Dinner dishes, Nick\'s check, Rotate Array',
  'Introduction to Linked List',
  'Types of Linked List',
  'Insertion of Linked List - Part 1: Product ID Insertion in Inventory',
  'Insertion of Linked List - Part 2: Task ID Management System, Adding a Task at a Specific Position',
  'Deletion of Linked List - Part 1: Deleting Tasks in a Task Management System',
  'Deletion of Linked List - Part 2: Managing Completed Tasks in a Project Management System',
  'Traversal of Linked List: Finding the Critical Task in a Project Workflow',
  'Problems on Linked List - 1: Reversing a Playlist, Reverse Linked List',
  'Problems on Linked List - 2: Reorganizing Job Priorities in a Task Manager, Swapping Nodes in a Linked List',
  'Problems on Linked List - 3: Removing Outdated Task by Deadline, Remove Nth Node From End of List',
  'Problems on Linked List - 4: Swapping Tasks in Pairs in a Scheduler, Odd Even Linked List',
  'Problems on Linked List - 5: Merging Patient Queues in a Hospital, Merge Two Sorted Lists',
  'Introduction to Recursion and its types: Fibonacci Number',
  'Problems on Recursion - 1: Calculating the Total Revenue of Orders, The Fibonacci Sequence for Future Engineers, Pow(x, n)',
  'Problems on Recursion - 2: Finding the Greatest Common Divisor in Ancient Math, Finding the Mighty Element in the Forest, Power of Three',
  'Introduction to Stack',
  'Stack Operations',
  'Stack - Array Implementation: Airport Baggage Handling System, Min Stack',
  'Stack - Linked List Implementation: Library Book Management System',
  'Introduction to Evaluation Expression',
  'Conversion of Infix to Postfix Expression: Expression Converter in a Calculator Application',
  'Evaluation of Postfix Expression: Expression Evaluator in a Calculator Application, Evaluate Reverse Polish Notation',
  'Problems on Stack - 1: Undo Operation in a Text Editor, Weather Forecasting Application, Valid Parentheses',
  'Problems on Stack - 2: Evaluating Redundant Brackets, Valid Parenthesis String',
  'Problems on Stack - 3: Fixing Unbalanced Parentheses, Minimum Remove to Make Valid Parentheses',
  'Introduction to Queue',
  'Queue - Array Implementation: Ticket Booking System',
  'Queue - Linked List Implementation: Customer Support Ticketing System',
  'Problems on Queues - 1: File Version Management, Implement Queue using Stacks',
  'Problems on Queues - 2: Order Processing System, Implement Stack using Queues',
  'Introduction to Trees and Tree Terminologies',
  'Introduction to Binary Tree',
  'Binary Tree Insertion: Organizing a Cricket Tournament',
  'Binary Tree Traversals - BFS',
  'Binary Tree Traversals - DFS: Tournament Ranking System in Cricket, Cricket Tournament Bracket Management',
  'Problems on Binary Tree - 1: Library Book Collection Tracker, Analyzing Tournament Levels in a Cricket Championship, Maximum Depth of Binary Tree',
  'Problems on Binary Tree - 2: Finding the Common Captain in a Cricket Team\'s Hierarchy, Lowest Common Ancestor of a Binary Tree',
  'Problems on Binary Tree - 3: Cricket Team Hierarchy Visualization, Binary Tree Right Side View',
  'Problems on Binary Tree - 4: Summing Book IDs from Leaf Categories, Sum of Left Leaves',
  'Problems on Binary Tree - 5: Observing Strategy Patterns, Binary Tree Zigzag Level Order Traversal',
  'Introduction to Binary Search Tree',
  'Binary Search Tree Insertion: Organizing a Library Collection, Insert into a Binary Search Tree',
  'Binary Search Tree Traversals: Searching an element in BST, Search in a Binary Search Tree',
  'Binary Search Tree Deletion: Delete Node in a BST',
  'Problems on Binary Search Tree - 1: Trim a BST, Lowest Common Ancestor of a Binary Search Tree',
  'Problems on Binary Search Tree - 2: Kth smallest element in BST, Kth Smallest Element in a BST',
  'Problems on Binary Search Tree - 3: Loan Repayment Verification System, Convert Sorted List to Binary Search Tree',
  'Problems on Binary Search Tree - 4: Validate BST, Validate Binary Search Tree',
  'Introduction to Heaps',
  'Types of Heaps',
  'Heap Operations - 1',
  'Heap Operations - 2',
  'Priority Queue: Ayushi and the Magical Chocolate Piles',
  'Problems on Priority Queue - 1: Leaderboard Ranking in a Coding Contest, Reordering Packages in a Delivery Center',
  'Problems on Priority Queue - 2: Most Popular Products in an Online Store',
  'Problems on Priority Queue - 3: Rescue Drones, Identifying Nearest Emergency Locations',
  'Problems on Priority Queue - 4: Merging K Sorted Lists of Student Marks',
  'Bubble Sort: Sorting Books by Page Count',
  'Insertion Sort and Selection Sort: Arranging Students by Marks, Sorting Exam Scores Using Selection Sort',
  'Heap Sort',
  'Problems on Sorting - 1: Sorting Defective, Regular, and Premium Products in a Factory',
  'Problems on Sorting - 2: Wiggle Sorting of Product Prices',
  'Introduction to Graphs',
  'Graph Representations: City Transport Network, City Transportation System',
  'Graph Traversal - BFS: City Infrastructure Planning, Find the Town Judge',
  'Graph Traversal - DFS: Exploring City Routes, Find Center of Star Graph',
  'Problems on Graphs - 1: Road Network Connectivity',
  'Problems on Graphs - 2: Access to Libraries in HackerLand',
  'Problems on Graphs - 3: Shortest Route Finder in a City',
  'Problems on Graphs - 4: Edge Removal for Connected Components',
  ...TOPIC_TRACKER_SPECIAL_TOPICS,
];

export const PSTJ_TOPIC_TRACKER_TOPICS = [
  'Orientation: History of Java, Features, Java vs other languages',
  'Introduction to Java',
  'Platform Independence: JVM role, WORA concept',
  'Java Environment: JVM, JRE, JDK, bytecode flow',
  'Java Program Structure: Class structure, main method, source vs class file',
  'Data Types: Primitive & non-primitive types',
  'Variables & Type Conversion: Implicit & explicit casting',
  'Operators: Arithmetic, relational, logical, assignment, unary',
  'DFR: Scanner, System.out methods',
  'Control Structures - Decision: if, if-else, switch',
  'Decision making programs - 1',
  'Decision making programs - 2',
  'Control Structures - Loops: for, while, do-while',
  'Variable Scope & Lifetime: Local, instance, static',
  'Basic Programs: Simple Java programs (I/O, operators)',
  'Control Structure Programs: Conditional & loop-based problems',
  'Control Structure Programs - 2: Menu-driven Java program',
  'Control Structure Programs - 3: Debugging basic errors, MCQs',
  'Arrays - Basics: 1D array declaration, initialization',
  'Operations and Problems on 1D Array: Traversal, insertion',
  'Operations and Problems on 1D Array: Passing arrays to methods',
  'Operations and Problems on 1D Array: Search, sort, max/min',
  '2D Arrays: Matrix representation',
  'Array Operations and Problems on 2D Array - 1',
  'Array Operations and Problems on 2D Array - 2: Utility-based programs',
  'Array Operations and Problems on 2D Array - 3',
  'Strings and Operations: length, substring, compare',
  'Problems on String',
  'Problems on String - 2: Reverse, palindrome',
  'Methods - Basics: Syntax, access modifiers',
  'Parameter Passing: Call by value',
  'Return Mechanisms: Returning values & objects',
  'Recursion - Concept: Base & recursive case',
  'Problems on Method and Recursion: Factorial, Fibonacci',
  'Problems on Method and Recursion - 2',
  'Package Access Rules: User-defined packages',
  'Access Modifiers: Public, protected',
  'OOP Overview: Need for OOP',
  'Classes & Objects: Object creation',
  'Encapsulation: Data hiding',
  'Constructors: Default & parameterized',
  'Static Members: Static variables & methods',
  'this Keyword & GC: Object referencing',
  'Inheritance Basics: IS-A relationship',
  'Types of Inheritance: Single, multilevel, hierarchical',
  'super & final: Constructor chaining',
  'Polymorphism: Compile-time vs runtime',
  'Method Overloading: Signature variations',
  'Method Overriding: Dynamic binding',
  'Abstraction, Abstract Classes: Abstract methods',
  'Interfaces, Multiple Inheritance',
  'Interface Programs: Implementation examples',
  'Problems on OOPs: Real-time OOP design',
  'Problems on OOPs - 2: OOP design questions',
  'Exception Basics: Runtime errors, exception overview',
  'Types of Exceptions: Checked & unchecked',
  'try-catch: Single & multiple catch',
  'throw & throws: Explicit throwing',
  'finally Block: Resource cleanup',
  'User-Defined Exceptions: Custom exception class',
  'Multithreading Overview: Need for multithreading',
  'Process vs Thread: Differences',
  'Thread Life Cycle: Code analysis',
  'Thread Class: Extending Thread',
  'Runnable Interface: Implementing Runnable',
  'Synchronization: Critical section',
  'Thread Programs: Race condition demo',
  'Unit Testing and Code Review',
  'Java I/O Overview: Streams & readers',
  'FileReader: Reading text files',
  'FileWriter: Writing files',
  'BufferedWriter: Performance',
  'IOException: I/O errors',
  'Try-with-Resources: Auto close',
  'File Class: File properties',
  'File Operations: Create, delete',
  'Directory Handling: Listing directories',
  'Collections Overview: Need for collections',
  'List Interface: ArrayList',
  'Set & Map Basics: HashSet, HashMap',
  'Collections Lab: CRUD operations',
  ...TOPIC_TRACKER_SPECIAL_TOPICS,
];

export const PSTP_TOPIC_TRACKER_TOPICS = [
  'Introduction to Python',
  'Input and Output - 1: Automated System Greeting for New Users, Automated Coffee Machine Startup with Repeated Humorous Message',
  'Type Casting: Student Information Management System, User Registration System',
  'ASCII Values: Character Analysis Tool, ASCII Decoder Tool',
  'Introduction to Operators',
  'Problems on Operators - 1: Fencing and Carpet Calculation for a Fighting Ground, Store water',
  'Problems on Operators - 2: Fitness App, The Clock System Bulb Switcher',
  'Problems on Operators - 3: Profit Calculation for The Herald Newspaper, Opening the Enchanted Door',
  'Problems on Operators - 4: Team Games with Ross Geller, Goal Tracker',
  'Introduction to Decision making',
  'Problems on Decision Making - 1: Temperature Check for Outdoor Activities, Event Scheduling for Leap Year Celebrations',
  'Problems on Decision Making - 2: Narnian Alphabet Helper, Rock, Paper, Scissor, Add Digits',
  'Problems on Decision Making - 3: Joey\'s Quest for the Trendy Meatball Sandwich, Car Rental Charges for a Travel Agency',
  'Problems on Decision Making - 4: Choosing the Tallest Skyscraper, Selecting the Second Best Candidate',
  'Problems on Decision Making - 5',
  'Introduction to Looping',
  'Problems on Looping - 1: Adam\'s Charity, Car Speed, Missing Number',
  'Problems on Looping - 2: Next Leap Year, Quality Check for Premium Products, Nth Digit',
  'Problems on Looping - 3: Virus Growth Prediction, Cricket Run Rate Tracker, Perfect Number',
  'Problems on Looping - 4: Building a Digital Staircase for a Smart Home System, Stage Lighting Arrangement for a Theater Performance, Valid Perfect Square',
  'Introduction to List, Set',
  'Introduction to Tuples and Dictionary',
  'Problems on List - 1: Insertion of New Product IDs, Second occurrence, Three Consecutive Odds',
  'Problems on List - 2: Dinner dishes, Nick\'s check, Rotate Array',
  'Problems on List - 3: The lost digit, Alice\'s Magical shoes!, Find First and Last Position of Element in Sorted Array',
  'Problems on List - 4: Data Recovery - Reversing the Sensor Log, Playing with numbers, Maximum Subarray',
  'Problems on List - 5: Unsold products, Finding the Median of Positive Product IDs, Number of Subarrays With LCM Equal to K',
  'Problems on 2D List - 1: Merging Attendance Records, Irene\'s Audience Arrangement Checker, Transpose Matrix',
  'Problems on 2D List - 2: Robotic Warehouse Navigation - Snake Pattern Traversal, Identifying Maximum Defect Levels in Production Batches, Spiral Matrix',
  'Problems on 2D List - 3: Counting Sorted Production Lines, Power Grid Monitoring - Computing Diagonal Load Balances, Diagonal Traverse',
  'Problems on 2D List - 4: Image Rotation Feature, Security Camera Image Processing System',
  'Introduction to Strings',
  'Problems on Strings - 1: Character count, Lower case count, Fizz Buzz',
  'Problems on Strings - 2: Fannys occurrences, Kindergarten Sentence Building, Longest Uncommon Subsequence I',
  'Problems on Strings - 3: Seat Allocation Check for Graduation Ceremony, Identifying Overused Letters, Is Subsequence',
  'Problems on Strings - 4: Data Compression for Server Log Optimization, Reversing Words for a Speech Teleprompter, To Lower Case',
  'Introduction to Functions',
  'Problems on Functions - 1: Perfect Number Detection for Vault Security, Calculating the Total of Unique Products Sold, Number of Common Factors',
  'Problems on Functions - 2: Finding the Leaders in Sales Data, Secure Login System Password Validator, Count Odd Numbers in an Interval Range',
  'Problems on Functions - 3: Efficient Budget Allocation for Project Expenses, Switching Letters in a Text, Sign of the Product of an Array',
  'Introduction to Recursion',
  'Problems on Recursion - 1: Calculating Factorials for the Space Expedition, Calculating the Total Revenue of Orders, Pow(x, n)',
  'Problems on Recursion - 2: The Fibonacci Sequence for Future Engineers, Finding the Greatest Common Divisor in Ancient Math, Fibonacci Number',
  'Problems on Recursion - 3: Finding the Mighty Element in the Forest, Counting Active Bits in a Device Monitoring System, Power of Three',
  'Problems on Recursion - 4: Recursive String Length Calculator, Recursive Sum of Array Elements',
  'Basics of File Handling',
  'Writing and Appending to Files',
  'Practical Applications and Error Handling',
  'Introduction to OOPS',
  'Class and Objects, Constructors',
  'Problems on class and objects - 1: Sports Venue Information System',
  'Problems on class and objects - 2: Car Dealership Management System',
  'Encapsulation',
  'Access specifiers',
  'Problems on Encapsulation - 1: Cricket Player Statistics Management',
  'Problems on Encapsulation - 2: Cricket Player Management',
  'Inheritance and its types',
  'Problems on Inheritance - 1: University Student Information System',
  'Problems on Inheritance - 2: Automobile Inventory Management System',
  'Polymorphism',
  'Problems on Polymorphism - 1: Cricket Match Tracker',
  'Problems on Polymorphism - 2: Cricket Player Profile with Role-Specific Details',
  'Abstraction',
  'Problems on Abstraction - 1: Online Payment System for Different Payment Methods',
  'Problems on Abstraction - 2: Library Management System for Book Details and Borrowing Status',
  'Introduction to Data Visualization',
  'NumPy Basics',
  'Pandas Data Structures',
  'Data Cleaning with Pandas',
  'Matplotlib: Line & Bar Charts',
  'Matplotlib: Histograms & Scatter',
  'Matplotlib: Customization Techniques',
  'Seaborn: Introduction + Heatmaps',
  'Seaborn: Pair Plots & Regression Plots',
  'Seaborn: Plot Customization & Styling',
  ...TOPIC_TRACKER_SPECIAL_TOPICS,
];

export const DSAP_TOPIC_TRACKER_TOPICS = [
  'Introduction to Linked List',
  'Types of Linked List',
  'Insertion of Linked List - Part 1: Product ID Insertion in Inventory',
  'Insertion of Linked List - Part 2: Task ID Management System, Adding a Task at a Specific Position',
  'Deletion of Linked List - Part 1: Deleting Tasks in a Task Management System',
  'Deletion of Linked List - Part 2: Managing Completed Tasks in a Project Management System',
  'Traversal of Linked List: Finding the Critical Task in a Project Workflow',
  'Problems on Linked List - 1: Reversing a Playlist, Reverse Linked List',
  'Problems on Linked List - 2: Reorganizing Job Priorities in a Task Manager, Middle of the Linked List',
  'Introduction to Stack',
  'Stack - Array Implementation: Airport Baggage Handling System, Min Stack',
  'Stack - Linked List Implementation: Library Book Management System',
  'Conversion of Infix to Postfix Expression: Expression Converter in a Calculator Application',
  'Evaluation of Postfix Expression: Expression Evaluator in a Calculator Application, Evaluate Reverse Polish Notation',
  'Problems on Stack - 1: Undo Operation in a Text Editor, Weather Forecasting Application, Valid Parentheses',
  'Problems on Stack - 2: Evaluating Redundant Brackets, Minimum Remove to Make Valid Parentheses',
  'Introduction to Queue',
  'Queue - Array Implementation: Ticket Booking System',
  'Queue - Linked List Implementation: Customer Support Ticketing System',
  'Problems on Queues - 1: File Version Management, Implement Queue using Stacks',
  'Problems on Queues - 2: Order Processing System, Implement Stack using Queues',
  'Introduction to Trees and Tree Terminologies',
  'Introduction to Binary Tree and AVL Tree',
  'Binary Tree Insertion: Organizing a Cricket Tournament',
  'Binary Tree Traversals - BFS',
  'Binary Tree Traversals - DFS: Tournament Ranking System in Cricket, Cricket Tournament Bracket Management',
  'Problems on Binary Tree - 1: Library Book Collection Tracker, Analyzing Tournament Levels in a Cricket Championship, Binary Tree Inorder Traversal',
  'Problems on Binary Tree - 2: Finding the Common Captain in a Cricket Team\'s Hierarchy, Maximum Depth of Binary Tree',
  'Problems on Binary Tree - 3: Cricket Team Hierarchy Visualization, Path Sum',
  'Problems on Binary Tree - 4: Summing Book IDs from Leaf Categories, Minimum Depth of Binary Tree',
  'Problems on Binary Tree - 5: Observing Strategy Patterns, Sum of Left Leaves',
  'Introduction to Binary Search Tree',
  'Binary Search Tree Insertion: Organizing a Library Collection',
  'Binary Search Tree Traversals: Searching an element in BST',
  'Binary Search Tree Deletion: Binary Search Tree Deletion',
  'Problems on Binary Search Tree - 1: Trim a BST, Search in a Binary Search Tree',
  'Problems on Binary Search Tree - 2: Kth smallest element in BST, Insert into a Binary Search Tree',
  'Problems on Binary Search Tree - 3: Root to leaf path sum equal to a given number, Lowest Common Ancestor of a Binary Search Tree',
  'Problems on Binary Search Tree - 4: Validate BST',
  'Introduction to Graphs',
  'Graph Representations: City Transport Network, City Transportation System',
  'Graph Traversal - BFS: City Infrastructure Planning',
  'Graph Traversal - DFS: Exploring City Routes',
  'Shortest Path Algorithms - Dijkstra\'s Algorithm: Road Network Connectivity',
  'Shortest Path Algorithms - Bellman Ford Algorithm: Access to Libraries in HackerLand',
  'Problems on Graphs - 1: Road Network Connectivity, Find Center of Star Graph',
  'Problems on Graphs - 2: Access to Libraries in HackerLand, Ransom Note',
  'Problems on Graphs - 3: Shortest Route Finder in a City',
  'Problems on Graphs - 4: Edge Removal for Connected Components',
  'Problems on Graphs - 5: Finding a Mother Vertex in a Graph',
  'Problems on Graphs - 6: Identifying Cycles in Urban Road Networks',
  'Problems on Graphs - 7: Counting Islands',
  'Binary Search: Smart Library - Finding Books with Binary Search',
  'Problems on Searching - 1: Treasure Hunt - Searching in a Rotated Map',
  'Problems on Searching - 2: Log Analysis - Finding First and Last Occurrence of an Event, Search Insert Position',
  'Problems on Searching - 3: Product Inventory Search in a Warehouse, Find First and Last Position of Element in Sorted Array',
  'Problems on Searching - 4: Finding the Oldest Artifact in a Rotated Historical Timeline, Find Peak Element',
  'Problems on Searching - 5: Finding the Highest Mountain Peak in a Terrain Map, Search in Rotated Sorted Array',
  'Problems on Searching - 6: Finding Two Numbers Whose Squares Sum to a Given Value, Find Minimum in Rotated Sorted Array',
  'Bubble Sort: Sorting Books by Page Count',
  'Insertion Sort: Arranging Students by Marks',
  'Selection Sort: Sorting Exam Scores Using Selection Sort',
  'Quick Sort: Efficient Price Sorting for an E-Commerce Sale using Quick Sort',
  'Merge Sort: Sorting Student Scores using Merge Sort',
  'Problems on Sorting - 1: Merging Sorted Inventories of a Warehouse',
  'Problems on Sorting - 2: Sorting Defective, Regular, and Premium Products in a Factory',
  'Introduction to Heaps',
  'Types of Heaps',
  'Priority Queue: Ayushi and the Magical Chocolate Piles',
  'Problems on Priority Queue - 1: Leaderboard Ranking in a Coding Contest, Reordering Packages in a Delivery Center',
  'Problems on Priority Queue - 2: Most Popular Products in an Online Store',
  'Introduction to Hashing: Customer Orders Management System',
  'Problems on Hashing - 1: Employee Salary Management System, Ransom Note',
  'Problems on Hashing - 2: University Student Marks Database, Number of Substrings Containing All Three Characters',
  'Problems on Hashing - 3: Efficient Library Book Tracking System, Valid Anagram',
  ...TOPIC_TRACKER_SPECIAL_TOPICS,
];

export const LRRE_TOPIC_TRACKER_TOPICS = [
  'Introduction to Logical Reasoning: Types of reasoning, exam patterns, problem-solving approach',
  'Data Arrangements - Linear: Single row, ordering, positional constraints',
  'Data Arrangements - Double Row: Facing directions, opposite positions',
  'Circular Arrangements: Clockwise, anti-clockwise, inward & outward facing',
  'Complex Arrangements: Mixed arrangements, multiple conditions',
  'Matrix & Multi-dimensional Arrangements: Grid-based puzzles',
  'Tabular Reasoning: Table-based logical deductions',
  'Advanced Seating Arrangement Practice: Mixed arrangement case studies',
  'Blood Relations - Basics: Family tree, direct relations',
  'Blood Relations - Advanced: Coded relations, descriptive questions',
  'Coding-Decoding - Letter Coding: Alphabet shifts, patterns',
  'Coding-Decoding - Number Coding: Numeric transformations',
  'Coding-Decoding - Mixed Coding: Substitution, symbol coding',
  'Analogy & Odd-One-Out: Letter, number and figure analogy',
  'Alpha Numeric Series: Series completion and missing elements',
  'Cryptarithmetic: Digit substitution puzzles',
  'Visual Reasoning - Basics: Mirror image, water image',
  'Visual Reasoning - Advanced: Paper folding, paper cutting, figure sequence',
  'Non-Verbal Reasoning: Pattern recognition, embedded figures',
  'Mixed Logical Reasoning Practice: Timed reasoning set',
  'Logical Connectives: If-Then logic, implications',
  'Conditional Statements: Necessary & sufficient conditions',
  'Syllogisms: Venn approach, statement-conclusion',
  'Venn Diagram Applications: Set relationships and problems',
  'Direction Sensing: Relative positioning, shortest path',
  'Cubes & Spatial Puzzles: Cube counting, rotations',
  'Calendars - I: Odd Days, Leap Years, Types of Years, Finding Day of the Week, Basic Calendar Concepts',
  'Calendars - II: Repeated Calendars, Calendar-Based Shortcuts, Previous/Next Day Problems, Date Difference, Advanced Calendar Applications & Placement Questions',
  'Clocks - I: Clock Basics, Hour & Minute Hand Movement, Angle Between Hands, Coincidence Problems, Right Angle Problems',
  'Clocks - II: Gain & Loss of Time, Mirror Clocks, Time Calculation Shortcuts, Clock-Based Puzzle Questions, Advanced Placement Problems',
  'Decision Making & Critical Reasoning: Logical judgement, assumptions, conclusions',
  'Professional Skills - Personal Presentation: First impression, grooming',
  'Body Language & Workplace Etiquette: Posture, gestures, professionalism',
  'Business Communication Basics: Formal communication, email etiquette',
  'Attention to Detail: Error spotting, observation exercises',
  'Time Management & Productivity: Prioritization, planning techniques',
  'Team Building & Collaboration: Interpersonal coordination',
  'Group Discussion Fundamentals: GD rules, evaluation criteria',
  'Group Discussion Practice - I: Mock GD with feedback',
  'Group Discussion Practice - II: Advanced GD scenarios',
  'Resume Building: Resume structure, ATS basics, formatting',
  'Resume Review Workshop: Resume review and improvement',
  'Personal Interview - HR, Behavioral Round: Tell me about yourself, HR questions, STAR method, competency questions',
  'Mock Interview Session: Panel interview with evaluation',
  'Placement Readiness Assessment: Comprehensive LR test, GD, PI feedback and action plan',
  ...TOPIC_TRACKER_SPECIAL_TOPICS,
];

export const QAVA_TOPIC_TRACKER_TOPICS = [
  'Numbers system: Number system, Power cycle',
  'Numbers system: Remainder cycle, Factors, Multiples',
  'Numbers system: HCF and LCM',
  'Percentages, Simple interest and Compound interest: Percentages as Fractions and Decimals, Percentage Increase / Decrease',
  'Percentages, Simple interest and Compound interest: Simple Interest, Compound Interest',
  'Percentages, Simple interest and Compound interest: Relation Between Simple and Compound Interest',
  'Ratio and Proportion: Ratio, Proportion',
  'Ratio and Proportion: Variation, Simple equations',
  'Ratio and Proportion: Problems on Ages',
  'Profit and Loss, Partnerships and Averages: Vocabulary Demystified',
  'Profit and Loss, Partnerships and Averages: Synonyms and Antonyms, Word Analogy',
  'Profit and Loss, Partnerships and Averages: Miscellaneous Vocabulary',
  'Logarithms, Progressions, Geometry and Quadratic equations: Logarithm, Arithmetic Progression, Geometric Progression',
  'Logarithms, Progressions, Geometry and Quadratic equations: Geometry, Mensuration',
  'Logarithms, Progressions, Geometry and Quadratic equations: Quadratic Equations',
  'Time and Work: Work with different efficiencies, Pipes and cisterns',
  'Time and Work: Work equivalence',
  'Time and Work: Division of wages',
  'Time, Speed and Distance: Basics of time, speed and distance, Relative speed',
  'Time, Speed and Distance: Problems based on trains, Problems based on boats and streams',
  'Time, Speed and Distance: Problems based on races',
  'Permutation, Combination and Probability: Data Interpretation - Tables, Data Interpretation - Pie Chart',
  'Permutation, Combination and Probability: Data Interpretation - Bar Graph',
  'Permutation, Combination and Probability: Data Sufficiency',
  'Sentence correction: Subject-Verb Agreement, Modifiers, Parallelism',
  'Sentence correction: Pronoun-Antecedent Agreement, Verb Time Sequences, Comparisons',
  'Sentence correction: Prepositions, Determiners',
  'Sentence completion and Para-jumbles: Pro-active thinking, Reactive thinking (signpost words, root words, prefix suffix, sentence structure clues)',
  'Sentence completion and Para-jumbles: Fixed jumbles',
  'Sentence completion and Para-jumbles: Anchored jumbles',
  'Vocabulary: Basic terminologies in profit and loss, Partnership',
  'Vocabulary: Averages',
  'Vocabulary: Weighted average, Mixtures and alligations',
  'Articles, Prepositions and Interrogatives: Definite and Indefinite Articles, Omission of Articles',
  'Articles, Prepositions and Interrogatives: Prepositions, Compound Prepositions and Prepositional Phrases',
  'Articles, Prepositions and Interrogatives: Interrogatives',
  'Voice and speech: Active Voice and Passive Voice',
  'Voice and speech: Direct Speech',
  'Voice and speech: Indirect Speech',
  'Reading comprehension: Speed Reading Strategies',
  'Reading comprehension: RC - Types and Tackling Strategies - 1',
  'Reading comprehension: RC - Types and Tackling Strategies - 2',
  'Critical Reasoning: Argument - Identifying the Different Parts (Premise, assumption, conclusion) - 1',
  'Critical Reasoning: Argument - Identifying the Different Parts (Premise, assumption, conclusion) - 2',
  'Critical Reasoning: Types of Questions for QAVA',
  ...TOPIC_TRACKER_SPECIAL_TOPICS,
];

const TOPIC_CATALOG_BY_SUBJECT_CODE = {
  [IDSA_SUBJECT.code]: IDSA_TOPIC_TRACKER_TOPICS,
  [PSTJ_SUBJECT_CODE]: PSTJ_TOPIC_TRACKER_TOPICS,
  [PSTP_SUBJECT.code]: PSTP_TOPIC_TRACKER_TOPICS,
  [DSAP_SUBJECT.code]: DSAP_TOPIC_TRACKER_TOPICS,
  [LRRE_SUBJECT_CODE]: LRRE_TOPIC_TRACKER_TOPICS,
  [QAVA_SUBJECT_CODE]: QAVA_TOPIC_TRACKER_TOPICS,
};

export const subjectUsesTopicCatalog = (subjectCode) =>
  Boolean(subjectCode && TOPIC_CATALOG_BY_SUBJECT_CODE[subjectCode?.trim()]);

export const getTopicOptionsForSubject = (subjectCode) => {
  const code = subjectCode?.trim();
  if (!code || !TOPIC_CATALOG_BY_SUBJECT_CODE[code]) return null;
  return TOPIC_CATALOG_BY_SUBJECT_CODE[code];
};

export const isAllowedTopicForSubject = (subjectCode, topic) => {
  const options = getTopicOptionsForSubject(subjectCode);
  if (!options) return true;
  if (!topic?.trim()) return true;
  return options.includes(topic.trim());
};
